[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "sysimpactcv"
version = "0.0.1"

[tool.setuptools]
packages = ["sysimpactcv"]        # ← ONLY install this package